# Generated by Django 5.2.17 on 2026-09-13 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=180)),
                ('set_name', models.CharField(blank=True, db_index=True, max_length=180)),
                ('set_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('card_number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('condition', models.CharField(choices=[('M', 'Mint'), ('NM', 'Near mint'), ('LP', 'Lightly played'), ('MP', 'Moderately played'), ('HP', 'Heavily played')], max_length=2)),
                ('card_language', models.CharField(choices=[('th', 'Thai'), ('en', 'English'), ('ja', 'Japanese')], max_length=2)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('ultra', 'Ultra rare'), ('secret', 'Secret rare')], max_length=16)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('THB', 'Thai baht'), ('USD', 'US dollar')], max_length=3)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='listings/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('hidden', 'Hidden')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='marketplace.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listing_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_saved_listing')],
            },
        ),
    ]
