import type { User, Listing, ChatThread, Review } from './types';

export const SETS = [
  'Scarlet & Violet (SV01)', 'Paldea Evolved (SV02)', 'Obsidian Flames (SV03)',
  'Paradox Rift (SV04)', 'Paldean Fates (SV04.5)', 'Temporal Forces (SV05)',
  'Twilight Masquerade (SV06)', 'Crown Zenith', 'Silver Tempest',
  'Lost Origin', 'Astral Radiance', 'Brilliant Stars',
  'ポケモンカード151', 'レイジングサーフ', 'シャイニートレジャーex',
  'ステラミラクル', 'マスカーニャex', 'Ancient Roar / Future Flash',
];

export const CURRENT_USER: User = {
  id: 'me',
  name: 'ธนพล สุขใจ',
  email: 'thanapol@email.com',
  avatar: 'ธ',
  role: 'business',
  verified: true,
  verifiedType: 'id',
  rating: 4.9,
  reviewCount: 128,
  totalSold: 342,
  joinedDate: '2022-03-15',
  location: 'กรุงเทพมหานคร',
  bio: 'ร้านการ์ด Pokémon ที่เชื่อถือได้ มีการ์ดทุกเซตให้เลือก พร้อมส่งทั่วประเทศ',
};

export const MOCK_USERS: User[] = [
  CURRENT_USER,
  {
    id: 'u2',
    name: 'นภัส รักการ์ด',
    email: 'napat@email.com',
    avatar: 'น',
    role: 'personal',
    verified: true,
    verifiedType: 'passport',
    rating: 4.7,
    reviewCount: 34,
    totalSold: 67,
    joinedDate: '2023-01-10',
    location: 'เชียงใหม่',
    bio: 'นักสะสมการ์ด Pokémon ตัวยง ชอบการ์ด Full Art และ Alt Art เป็นพิเศษ',
  },
  {
    id: 'u3',
    name: 'PokeShop BKK',
    email: 'pokeshop@email.com',
    avatar: 'P',
    role: 'business',
    verified: true,
    verifiedType: 'id',
    rating: 4.8,
    reviewCount: 512,
    totalSold: 2840,
    joinedDate: '2021-06-01',
    location: 'กรุงเทพมหานคร',
    bio: 'ร้านการ์ด Pokémon ใจกลางกรุงเทพฯ มีสต็อกการ์ดมากกว่า 50,000 ใบ รับซื้อ-ขาย-แลกเปลี่ยน',
  },
  {
    id: 'u4',
    name: 'Sakura Cards',
    email: 'sakura@email.com',
    avatar: 'S',
    role: 'business',
    verified: true,
    verifiedType: 'passport',
    rating: 4.6,
    reviewCount: 289,
    totalSold: 1203,
    joinedDate: '2022-09-14',
    location: 'ชลบุรี',
    bio: 'เชี่ยวชาญการ์ด Pokémon ภาษาญี่ปุ่น นำเข้าตรงจากญี่ปุ่นทุกเดือน',
  },
  {
    id: 'u5',
    name: 'มานะ เพชรดี',
    email: 'mana@email.com',
    avatar: 'ม',
    role: 'personal',
    verified: false,
    rating: 4.2,
    reviewCount: 8,
    totalSold: 12,
    joinedDate: '2024-01-05',
    location: 'ขอนแก่น',
    bio: 'ขายการ์ดส่วนตัวที่ไม่ได้ใช้แล้ว สภาพดีทุกใบ',
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1', sellerId: 'u3', sellerName: 'PokeShop BKK',
    sellerAvatar: 'P', sellerRole: 'business', sellerVerified: true, sellerRating: 4.8,
    productName: 'Charizard ex (Full Art)', set: 'Obsidian Flames (SV03)',
    setCode: '125/197', cardNumber: '125/197', condition: 'NM', language: 'en',
    rarity: 'secret', listedPrice: 8500, quantity: 1, status: 'active',
    gradientFrom: '#FF4500', gradientTo: '#FF8C00', typeIcon: '🔥',
    createdAt: '2024-08-20', views: 342, likes: 67,
  },
  {
    id: 'l2', sellerId: 'u4', sellerName: 'Sakura Cards',
    sellerAvatar: 'S', sellerRole: 'business', sellerVerified: true, sellerRating: 4.6,
    productName: 'ピカチュウex (Special Art)', set: 'ステラミラクル',
    setCode: '086/102', cardNumber: '086/102', condition: 'M', language: 'ja',
    rarity: 'secret', listedPrice: 12000, quantity: 2, status: 'active',
    gradientFrom: '#FFD700', gradientTo: '#FFA500', typeIcon: '⚡',
    createdAt: '2024-08-19', views: 519, likes: 124,
  },
  {
    id: 'l3', sellerId: 'me', sellerName: 'ธนพล สุขใจ',
    sellerAvatar: 'ธ', sellerRole: 'business', sellerVerified: true, sellerRating: 4.9,
    productName: 'Gardevoir ex (Alt Art)', set: 'Scarlet & Violet (SV01)',
    setCode: '205/198', cardNumber: '205/198', condition: 'NM', language: 'en',
    rarity: 'secret', listedPrice: 5200, quantity: 1, status: 'active',
    gradientFrom: '#9B59B6', gradientTo: '#E91E8C', typeIcon: '✨',
    createdAt: '2024-08-18', views: 287, likes: 89,
  },
  {
    id: 'l4', sellerId: 'u2', sellerName: 'นภัส รักการ์ด',
    sellerAvatar: 'น', sellerRole: 'personal', sellerVerified: true, sellerRating: 4.7,
    productName: 'Mew ex (Full Art)', set: 'Pokemon 151 (SV2.5)',
    setCode: '205/165', cardNumber: '205/165', condition: 'NM', language: 'ja',
    rarity: 'ultra', listedPrice: 3800, quantity: 1, status: 'active',
    gradientFrom: '#E91E8C', gradientTo: '#9C27B0', typeIcon: '🔮',
    createdAt: '2024-08-17', views: 201, likes: 45,
  },
  {
    id: 'l5', sellerId: 'u3', sellerName: 'PokeShop BKK',
    sellerAvatar: 'P', sellerRole: 'business', sellerVerified: true, sellerRating: 4.8,
    productName: 'Rayquaza VMAX (Alt Art)', set: 'Evolving Skies',
    setCode: '218/203', cardNumber: '218/203', condition: 'M', language: 'en',
    rarity: 'secret', listedPrice: 14500, quantity: 1, status: 'active',
    gradientFrom: '#06B6D4', gradientTo: '#0EA5E9', typeIcon: '🐉',
    createdAt: '2024-08-16', views: 678, likes: 201,
  },
  {
    id: 'l6', sellerId: 'u4', sellerName: 'Sakura Cards',
    sellerAvatar: 'S', sellerRole: 'business', sellerVerified: true, sellerRating: 4.6,
    productName: 'リザードンex (スペシャルアート)', set: 'Ancient Roar (SV4K)',
    setCode: '059/066', cardNumber: '059/066', condition: 'NM', language: 'ja',
    rarity: 'secret', listedPrice: 9800, quantity: 3, status: 'active',
    gradientFrom: '#FF6B35', gradientTo: '#FF4500', typeIcon: '🔥',
    createdAt: '2024-08-15', views: 445, likes: 112,
  },
  {
    id: 'l7', sellerId: 'u5', sellerName: 'มานะ เพชรดี',
    sellerAvatar: 'ม', sellerRole: 'personal', sellerVerified: false, sellerRating: 4.2,
    productName: 'Umbreon VMAX (Alt Art)', set: 'Evolving Skies',
    setCode: '215/203', cardNumber: '215/203', condition: 'LP', language: 'en',
    rarity: 'ultra', listedPrice: 6500, quantity: 1, status: 'active',
    gradientFrom: '#1A1A2E', gradientTo: '#16213E', typeIcon: '🌙',
    createdAt: '2024-08-14', views: 156, likes: 34,
  },
  {
    id: 'l8', sellerId: 'u2', sellerName: 'นภัส รักการ์ด',
    sellerAvatar: 'น', sellerRole: 'personal', sellerVerified: true, sellerRating: 4.7,
    productName: 'Miraidon ex (Special Art)', set: 'Scarlet & Violet (SV01)',
    setCode: '253/198', cardNumber: '253/198', condition: 'NM', language: 'en',
    rarity: 'secret', listedPrice: 4200, quantity: 2, status: 'active',
    gradientFrom: '#3B82F6', gradientTo: '#6366F1', typeIcon: '⚡',
    createdAt: '2024-08-13', views: 234, likes: 56,
  },
];

export const MOCK_CHATS: ChatThread[] = [
  {
    id: 'c1', listingId: 'l1', listingName: 'Charizard ex (Full Art)',
    gradientFrom: '#FF4500', gradientTo: '#FF8C00',
    buyerId: 'me', buyerName: 'ธนพล สุขใจ', buyerAvatar: 'ธ',
    sellerId: 'u3', sellerName: 'PokeShop BKK', sellerAvatar: 'P',
    listedPrice: 8500,
    messages: [
      { id: 'm1', senderId: 'me', senderName: 'ธนพล', text: 'สวัสดีครับ ยังมีการ์ดอยู่ไหมครับ?', timestamp: '10:30', type: 'message' },
      { id: 'm2', senderId: 'u3', senderName: 'PokeShop BKK', text: 'มีอยู่ครับ สภาพ NM แพ็คใหม่มาเลย', timestamp: '10:32', type: 'message' },
      { id: 'm3', senderId: 'me', senderName: 'ธนพล', text: 'ลดได้บ้างไหมครับ?', timestamp: '10:35', type: 'message' },
      { id: 'm4', senderId: 'me', senderName: 'ธนพล', text: '8000', timestamp: '10:35', type: 'offer', offerAmount: 8000 },
      { id: 'm5', senderId: 'u3', senderName: 'PokeShop BKK', text: 'ยอมรับข้อเสนอ 8,000 บาทครับ', timestamp: '10:40', type: 'offer_accepted', offerAmount: 8000 },
    ],
    negotiatedPrice: 8000,
    status: 'active',
    lastMessage: 'ยอมรับข้อเสนอ 8,000 บาทครับ',
    lastMessageTime: '10:40',
    unread: 1,
  },
  {
    id: 'c2', listingId: 'l2', listingName: 'ピカチュウex (Special Art)',
    gradientFrom: '#FFD700', gradientTo: '#FFA500',
    buyerId: 'me', buyerName: 'ธนพล สุขใจ', buyerAvatar: 'ธ',
    sellerId: 'u4', sellerName: 'Sakura Cards', sellerAvatar: 'S',
    listedPrice: 12000,
    messages: [
      { id: 'm6', senderId: 'me', senderName: 'ธนพล', text: 'ราคา 11,500 ได้ไหมครับ?', timestamp: 'เมื่อวาน', type: 'message' },
      { id: 'm7', senderId: 'u4', senderName: 'Sakura Cards', text: 'ขอโทษนะครับ ราคาตายตัวครับ', timestamp: 'เมื่อวาน', type: 'message' },
    ],
    status: 'active',
    lastMessage: 'ขอโทษนะครับ ราคาตายตัวครับ',
    lastMessageTime: 'เมื่อวาน',
    unread: 0,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1', reviewerId: 'u3', reviewerName: 'PokeShop BKK', reviewerAvatar: 'P',
    reviewerRole: 'business', rating: 5,
    comment: 'ซื้อขายรวดเร็ว การ์ดสภาพดีมาก โอนเงินไวดีครับ แนะนำเลย ⭐⭐⭐⭐⭐',
    date: '2024-08-10',
  },
  {
    id: 'r2', reviewerId: 'u2', reviewerName: 'นภัส รักการ์ด', reviewerAvatar: 'น',
    reviewerRole: 'personal', rating: 5,
    comment: 'บริการดีมาก ส่งของไว แพ็กการ์ดมิดชิด ไม่มีบุบเลย จะกลับมาซื้ออีกแน่นอน',
    date: '2024-08-05',
  },
  {
    id: 'r3', reviewerId: 'u4', reviewerName: 'Sakura Cards', reviewerAvatar: 'S',
    reviewerRole: 'business', rating: 4,
    comment: 'ซื้อขายสะดวก แต่การสื่อสารช้าไปหน่อย แต่โดยรวมดีครับ',
    date: '2024-07-28',
  },
  {
    id: 'r4', reviewerId: 'u5', reviewerName: 'มานะ เพชรดี', reviewerAvatar: 'ม',
    reviewerRole: 'personal', rating: 5,
    comment: 'ได้รับการ์ดตามที่บอก สภาพดีมาก ราคายุติธรรม ประทับใจมากครับ',
    date: '2024-07-20',
  },
];

export const MY_LISTINGS = MOCK_LISTINGS.filter(l => l.sellerId === 'me');
