# Generated by Django 5.2.17 on 2026-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
